"""
quarto_export.jl — Generate .qmd stub files for each textbook from the manifest JSON files.

Usage:
    julia --project=. src/quarto_export.jl [--stubs-only]

Options:
    --stubs-only   Generate lightweight stub .qmd files (no content, just frontmatter
                   and chapter list). Used in CI to satisfy Quarto's file references
                   before full chapter content has been generated.
"""

using JSON3

const PROJECT_ROOT = dirname(dirname(abspath(@__FILE__)))
const MANIFEST_PATHS = [
    joinpath(PROJECT_ROOT, "manifests", "part1.json"),
    joinpath(PROJECT_ROOT, "manifests", "part2.json"),
]
const GENERATED_DIR = joinpath(PROJECT_ROOT, "output", "generated")

# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────

"""Convert a textbook ID like "CORE-001" to the filename stem "core-001"."""
id_to_stem(id::String) = lowercase(id)

"""Build the output path for a textbook's .qmd file."""
qmd_path(id::String) = joinpath(GENERATED_DIR, "$(id_to_stem(id)).qmd")

"""Load all textbooks from both manifest files."""
function load_manifests()::Vector{Any}
    textbooks = Any[]
    for path in MANIFEST_PATHS
        if !isfile(path)
            @warn "Manifest not found: $path"
            continue
        end
        data = JSON3.read(read(path, String))
        for tb in data["textbooks"]
            push!(textbooks, tb)
        end
    end
    return textbooks
end

# ─────────────────────────────────────────────
# Stub generation
# ─────────────────────────────────────────────

"""
Generate a stub .qmd file for a textbook. The stub contains YAML frontmatter,
a brief description, and a table of contents listing all chapters. It satisfies
Quarto's requirement that every file referenced in _quarto.yml exists, without
requiring the full generated chapter content.
"""
function write_stub(tb)
    id    = string(tb["id"])
    title = string(tb["title"])
    desc  = get(tb, "description", "")
    track = get(tb, "track", "")

    chapters = get(tb, "chapters", Any[])

    lines = String[]
    push!(lines, "---")
    push!(lines, "title: \"$(title)\"")
    if !isempty(string(track))
        push!(lines, "subtitle: \"$(track)\"")
    end
    push!(lines, "---")
    push!(lines, "")
    if !isempty(string(desc))
        push!(lines, string(desc))
        push!(lines, "")
    end
    push!(lines, "## Table of Contents")
    push!(lines, "")
    for ch in chapters
        num   = get(ch, "chapter_number", "")
        chtitle = get(ch, "title", "")
        push!(lines, "$(num). $(chtitle)")
    end
    push!(lines, "")
    push!(lines, "> *Full chapter content will be generated by the textbook pipeline.*")
    push!(lines, "")

    mkpath(GENERATED_DIR)
    path = qmd_path(id)
    write(path, join(lines, "\n"))
    return path
end

# ─────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────

function main()
    stubs_only = "--stubs-only" in ARGS

    textbooks = load_manifests()
    if isempty(textbooks)
        @error "No textbooks found in manifests. Aborting."
        exit(1)
    end

    @info "Generating QMD files for $(length(textbooks)) textbooks → $GENERATED_DIR"

    generated = 0
    for tb in textbooks
        path = write_stub(tb)
        generated += 1
        @info "  wrote $(basename(path))"
    end

    @info "Done — generated $generated .qmd stub files."
end

main()
